version: '2.1'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    container_name: gitlab
    hostname: "docker.for.mac.localhost"  
    ports:
      - "2222:22"
      - "8080:80"
      - "4444:443"
      - '9090:9090'
    volumes:
      - './volumes/config:/etc/gitlab'
      - './volumes/logs:/var/log/gitlab'
      - './volumes/data:/var/opt/gitlab'
    depends_on:
      - runner
      - redis
      - postgres

  runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    container_name: gitlab_runner
    volumes:
      - ./volumes/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock:rw

  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    container_name: gitlab_postgresql
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_DB=gitlabhq_production
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    container_name: gitlab_redis
    command:
      - --loglevel warning
    volumes:
      - ./volumes/redis:/var/lib/redis
    restart: always
